import type { AtomDefinition, LessonDefinition } from '../types/domain';
import { makeTransform } from '../utils/transforms';

export const atomCatalog: Record<'H' | 'O' | 'C' | 'N', AtomDefinition> = {
  H: {
    element: 'H',
    label: 'Hydrogen',
    colorHex: '#5cc8ff',
    radius: 0.04,
    defaultValence: 1,
  },
  O: {
    element: 'O',
    label: 'Oxygen',
    colorHex: '#ff7c69',
    radius: 0.055,
    defaultValence: 2,
  },
  C: {
    element: 'C',
    label: 'Carbon',
    colorHex: '#7f8c8d',
    radius: 0.06,
    defaultValence: 4,
  },
  N: {
    element: 'N',
    label: 'Nitrogen',
    colorHex: '#8e7dff',
    radius: 0.055,
    defaultValence: 3,
  },
};

export const moleculeBuilderLesson: LessonDefinition = {
  id: 'molecule-builder',
  title: 'Molecule Builder',
  summary: 'Learners assemble small molecules together, inspect the resulting structure, and answer quick collaborative quiz prompts.',
  facilitatorPrompt:
    'Invite players to talk out loud about which atom should be central, how many bonding sites they expect, and what the geometry means physically.',
  targetPlayers: {
    min: 2,
    max: 4,
  },
  challenges: [
    {
      id: 'water-build',
      moleculeId: 'h2o',
      title: 'Build Water',
      formula: 'H2O',
      quickFact: 'Water forms a bent geometry because oxygen has two bonding pairs and two lone pairs.',
      learningGoal: 'Recognize that molecular geometry depends on how electron groups arrange around the central atom.',
      geometry: 'Bent',
      bondCount: 2,
      realWorldUse: 'Water is essential for life and dissolves many substances because of its polarity.',
      trayAtoms: ['O', 'H', 'H', 'N'],
      slots: [
        {
          slotId: 'water-center',
          label: 'Central atom',
          expectedElement: 'O',
          accepts: ['O'],
          bondOrder: 2,
          transform: makeTransform(0, 0, 0),
          isCentralAtom: true,
        },
        {
          slotId: 'water-h1',
          label: 'Hydrogen 1',
          expectedElement: 'H',
          accepts: ['H'],
          bondOrder: 1,
          transform: makeTransform(-0.16, 0, 0.14),
          isCentralAtom: false,
        },
        {
          slotId: 'water-h2',
          label: 'Hydrogen 2',
          expectedElement: 'H',
          accepts: ['H'],
          bondOrder: 1,
          transform: makeTransform(0.16, 0, 0.14),
          isCentralAtom: false,
        },
      ],
      quizQuestions: [
        {
          id: 'water-geometry',
          prompt: 'What molecular geometry does water have once assembled?',
          promptShort: 'Water geometry',
          answerOptionIds: ['linear', 'bent', 'tetrahedral'],
          options: [
            { id: 'linear', label: 'Linear' },
            { id: 'bent', label: 'Bent' },
            { id: 'tetrahedral', label: 'Tetrahedral' },
          ],
          correctOptionId: 'bent',
          explanation: 'The bonded atoms are arranged in a bent shape around oxygen.',
          conceptTag: 'geometry',
        },
        {
          id: 'water-bond-count',
          prompt: 'How many single bonds are present in water?',
          promptShort: 'Water bond count',
          answerOptionIds: ['1', '2', '4'],
          options: [
            { id: '1', label: '1' },
            { id: '2', label: '2' },
            { id: '4', label: '4' },
          ],
          correctOptionId: '2',
          explanation: 'Water has two O-H bonds.',
          conceptTag: 'bond-count',
        },
        {
          id: 'water-use',
          prompt: 'Which concept best matches why water is useful in biology?',
          promptShort: 'Water concept',
          answerOptionIds: ['nonpolar fuel', 'polar solvent', 'inert noble gas'],
          options: [
            { id: 'nonpolar fuel', label: 'Nonpolar fuel' },
            { id: 'polar solvent', label: 'Polar solvent' },
            { id: 'inert noble gas', label: 'Inert noble gas' },
          ],
          correctOptionId: 'polar solvent',
          explanation: 'Water is a polar solvent and supports transport in living systems.',
          conceptTag: 'usage',
        },
      ],
    },
    {
      id: 'carbon-dioxide-build',
      moleculeId: 'co2',
      title: 'Build Carbon Dioxide',
      formula: 'CO2',
      quickFact: 'Carbon dioxide is linear because the electron regions around carbon balance symmetrically.',
      learningGoal: 'Connect arrangement of atoms with a linear molecular geometry.',
      geometry: 'Linear',
      bondCount: 2,
      realWorldUse: 'Carbon dioxide appears in respiration, carbonation, and climate science discussions.',
      trayAtoms: ['C', 'O', 'O', 'H'],
      slots: [
        {
          slotId: 'co2-center',
          label: 'Central atom',
          expectedElement: 'C',
          accepts: ['C'],
          bondOrder: 4,
          transform: makeTransform(0, 0, 0),
          isCentralAtom: true,
        },
        {
          slotId: 'co2-o1',
          label: 'Oxygen left',
          expectedElement: 'O',
          accepts: ['O'],
          bondOrder: 2,
          transform: makeTransform(-0.22, 0, 0),
          isCentralAtom: false,
        },
        {
          slotId: 'co2-o2',
          label: 'Oxygen right',
          expectedElement: 'O',
          accepts: ['O'],
          bondOrder: 2,
          transform: makeTransform(0.22, 0, 0),
          isCentralAtom: false,
        },
      ],
      quizQuestions: [
        {
          id: 'co2-geometry',
          prompt: 'Which geometry fits carbon dioxide?',
          promptShort: 'CO2 geometry',
          answerOptionIds: ['bent', 'linear', 'trigonal'],
          options: [
            { id: 'bent', label: 'Bent' },
            { id: 'linear', label: 'Linear' },
            { id: 'trigonal', label: 'Trigonal planar' },
          ],
          correctOptionId: 'linear',
          explanation: 'The two oxygen atoms sit opposite each other around carbon.',
          conceptTag: 'geometry',
        },
        {
          id: 'co2-bond-count',
          prompt: 'How many bonded oxygen atoms connect to carbon in carbon dioxide?',
          promptShort: 'CO2 bond count',
          answerOptionIds: ['1', '2', '3'],
          options: [
            { id: '1', label: '1' },
            { id: '2', label: '2' },
            { id: '3', label: '3' },
          ],
          correctOptionId: '2',
          explanation: 'Carbon is bonded to two oxygen atoms.',
          conceptTag: 'bond-count',
        },
        {
          id: 'co2-use',
          prompt: 'What real-world context is carbon dioxide most connected with in this lesson?',
          promptShort: 'CO2 concept',
          answerOptionIds: ['respiration and climate', 'table salt crystals', 'metal corrosion only'],
          options: [
            { id: 'respiration and climate', label: 'Respiration and climate' },
            { id: 'table salt crystals', label: 'Table salt crystals' },
            { id: 'metal corrosion only', label: 'Metal corrosion only' },
          ],
          correctOptionId: 'respiration and climate',
          explanation: 'CO2 is central to respiration, ecosystems, and climate systems.',
          conceptTag: 'usage',
        },
      ],
    },
    {
      id: 'methane-build',
      moleculeId: 'ch4',
      title: 'Build Methane',
      formula: 'CH4',
      quickFact: 'Methane forms a tetrahedral arrangement that spreads four hydrogen atoms around carbon.',
      learningGoal: 'Understand how four bonding groups create a tetrahedral structure.',
      geometry: 'Tetrahedral',
      bondCount: 4,
      realWorldUse: 'Methane is the main component of natural gas and a greenhouse gas.',
      trayAtoms: ['C', 'H', 'H', 'H', 'H', 'O'],
      slots: [
        {
          slotId: 'ch4-center',
          label: 'Central atom',
          expectedElement: 'C',
          accepts: ['C'],
          bondOrder: 4,
          transform: makeTransform(0, 0, 0),
          isCentralAtom: true,
        },
        {
          slotId: 'ch4-h1',
          label: 'Hydrogen north',
          expectedElement: 'H',
          accepts: ['H'],
          bondOrder: 1,
          transform: makeTransform(0, 0, -0.22),
          isCentralAtom: false,
        },
        {
          slotId: 'ch4-h2',
          label: 'Hydrogen east',
          expectedElement: 'H',
          accepts: ['H'],
          bondOrder: 1,
          transform: makeTransform(0.22, 0, 0),
          isCentralAtom: false,
        },
        {
          slotId: 'ch4-h3',
          label: 'Hydrogen south',
          expectedElement: 'H',
          accepts: ['H'],
          bondOrder: 1,
          transform: makeTransform(0, 0, 0.22),
          isCentralAtom: false,
        },
        {
          slotId: 'ch4-h4',
          label: 'Hydrogen west',
          expectedElement: 'H',
          accepts: ['H'],
          bondOrder: 1,
          transform: makeTransform(-0.22, 0, 0),
          isCentralAtom: false,
        },
      ],
      quizQuestions: [
        {
          id: 'ch4-geometry',
          prompt: 'What geometry should learners identify for methane?',
          promptShort: 'CH4 geometry',
          answerOptionIds: ['linear', 'bent', 'tetrahedral'],
          options: [
            { id: 'linear', label: 'Linear' },
            { id: 'bent', label: 'Bent' },
            { id: 'tetrahedral', label: 'Tetrahedral' },
          ],
          correctOptionId: 'tetrahedral',
          explanation: 'Four bonded atoms around carbon create a tetrahedral arrangement.',
          conceptTag: 'geometry',
        },
        {
          id: 'ch4-bond-count',
          prompt: 'How many hydrogens bond to carbon in methane?',
          promptShort: 'CH4 bond count',
          answerOptionIds: ['2', '3', '4'],
          options: [
            { id: '2', label: '2' },
            { id: '3', label: '3' },
            { id: '4', label: '4' },
          ],
          correctOptionId: '4',
          explanation: 'Methane has four C-H bonds.',
          conceptTag: 'bond-count',
        },
        {
          id: 'ch4-use',
          prompt: 'Methane is most commonly associated with which application in this lesson?',
          promptShort: 'CH4 concept',
          answerOptionIds: ['natural gas', 'table sugar', 'liquid coolant'],
          options: [
            { id: 'natural gas', label: 'Natural gas' },
            { id: 'table sugar', label: 'Table sugar' },
            { id: 'liquid coolant', label: 'Liquid coolant' },
          ],
          correctOptionId: 'natural gas',
          explanation: 'Methane is the main component of natural gas.',
          conceptTag: 'usage',
        },
      ],
    },
  ],
};

export const lessonCatalog: Record<string, LessonDefinition> = {
  [moleculeBuilderLesson.id]: moleculeBuilderLesson,
};

export const getLessonDefinition = (lessonId: string): LessonDefinition => lessonCatalog[lessonId] ?? moleculeBuilderLesson;
